import { StyleSheet } from 'react-native';

export const navigationStyles = StyleSheet.create({
  footer: {
    height: 88,
    padding: 8,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
    alignSelf: 'stretch',
    borderTopWidth: 2,
    borderTopColor: '#E2E2E2',
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 4,
  },
  iconRow: {
    paddingLeft: 8,
    paddingRight: 8,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  navigationButton: {
    paddingLeft: 8,
    paddingRight: 8,
    width: 88,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  label: {
    textAlign: 'center',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 24,
  },
  trailDetailButton: {
    width: 283,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    borderRadius: 8,
    backgroundColor: '#00702F',
  },
  trailDetailButtonLabel: {
    color: '#FFF',
    textAlign: 'center',
    fontFamily: 'Inter',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '800',
    lineHeight: 32,
  },
});
